import sqlite3
import datetime
import os
import webbrowser
import tempfile
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
try:
    from fpdf import FPDF
except ImportError:
    FPDF = None

from db_connector import DBHandler

def generate_business_report(shop_name, period="Daily"):
    """
    Generates a printable PDF report with Matplotlib Analysis Charts.
    """
    if not FPDF:
        return "Error: FPDF library not found. Please install headers."

    try:
        desktop = os.path.join(os.environ['USERPROFILE'], 'Desktop')
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"HornERP_Analysis_{timestamp}.pdf"
        filepath = os.path.join(desktop, filename)
        
        conn = DBHandler.get_connection()
        cursor = conn.cursor()
        
        # --- TIMEZONE FIX (Match POS) ---
        tz_offset = datetime.timezone(datetime.timedelta(hours=5))
        now_pak = datetime.datetime.now(tz_offset)
        today_str = now_pak.strftime("%Y-%m-%d") # YYYY-MM-DD
        month_str = now_pak.strftime("%Y-%m")    # YYYY-MM

        # Logic for Period
        if period == "Daily":
            filter_clause = f"date_created LIKE '{today_str}%'"
            period_label = f"Daily Report ({today_str})"
        elif period == "Weekly":
            start_date = (now_pak - datetime.timedelta(days=7)).strftime("%Y-%m-%d")
            filter_clause = f"date(date_created) >= '{start_date}'"
            period_label = f"Weekly Report (Since {start_date})"
        elif period == "Monthly":
            filter_clause = f"date_created LIKE '{month_str}%'"
            period_label = f"Monthly Report ({month_str})"
        else:
            filter_clause = f"date_created LIKE '{today_str}%'"
            period_label = f"Daily Report ({today_str})"

        # 1. Stats (Revenue for Period)
        cursor.execute(f"SELECT SUM(total_amount) FROM offline_sales WHERE {filter_clause}")
        res = cursor.fetchone()
        revenue_amt = res[0] if res and res[0] else 0.0
        
        # 2. Daily Revenue Trend (Last 7 Days - Static Context)
        cursor.execute("""
            SELECT date(date_created), SUM(total_amount) 
            FROM offline_sales 
            GROUP BY date(date_created) 
            ORDER BY date(date_created) DESC LIMIT 7
        """)
        trend_data = cursor.fetchall() 
        
        # 3. Top Products (For Period)
        cursor.execute(f"""
            SELECT i.product_name, SUM(i.quantity) as qty 
            FROM offline_sale_items i
            JOIN offline_sales s ON i.sale_id = s.id
            WHERE {filter_clause.replace('date_created', 's.date_created')}
            GROUP BY i.product_name 
            ORDER BY qty DESC LIMIT 5
        """)
        top_products = cursor.fetchall()
        
        # 4. Detailed List (For Period)
        query_period = f"""
            SELECT s.id, s.date_created, s.customer_name, i.product_name, i.quantity, i.price
            FROM offline_sale_items i
            JOIN offline_sales s ON i.sale_id = s.id
            WHERE {filter_clause.replace('date_created', 's.date_created')}
            ORDER BY s.id ASC
        """
        cursor.execute(query_period)
        sales_data = cursor.fetchall()
        
        conn.close()


        class PDFReport(FPDF):
            def header(self):
                # Logo area (colored strip)
                self.set_fill_color(26, 35, 126) # #1A237E (Deep Blue)
                self.rect(0, 0, 210, 25, 'F') # Increased height slightly
                
                self.set_y(5) # Start text a bit down
                self.set_font('Arial', 'B', 20)
                self.set_text_color(255, 255, 255)
                self.cell(0, 8, shop_name, 0, 1, 'C')
                
                self.set_font('Arial', 'I', 10)
                self.set_text_color(200, 200, 200)
                self.cell(0, 5, "Enterprise Management System", 0, 1, 'C')
                self.ln(10)
            
            def footer(self):
                self.set_y(-15)
                self.set_font('Arial', 'I', 8)
                self.set_text_color(128, 128, 128)
                self.cell(0, 10, f'Page {self.page_no()} - Generated by Horn ERP', 0, 0, 'C')

        pdf = PDFReport()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # --- EXECUTIVE SUMMARY ---
        pdf.set_text_color(26, 35, 126)
        pdf.set_font('Arial', 'B', 16)
        pdf.cell(0, 10, period_label, 0, 1, 'L')
        
        # Revenue Box
        pdf.set_fill_color(240, 248, 255) # AliceBlue
        pdf.set_draw_color(26, 35, 126)
        pdf.set_line_width(0.5)
        pdf.rect(10, pdf.get_y(), 190, 20, 'DF')
        
        pdf.set_y(pdf.get_y() + 5)
        pdf.set_font('Arial', 'B', 14)
        pdf.cell(190, 10, f"Total Revenue: ${revenue_amt:,.2f}", 0, 1, 'C')
        pdf.ln(15)

        # --- CHARTS ---
        temp_dir = tempfile.gettempdir()
        chart1_path = os.path.join(temp_dir, f"chart1_{timestamp}.png")
        chart2_path = os.path.join(temp_dir, f"chart2_{timestamp}.png")

        # Layout: Row of 2 charts
        y_charts = pdf.get_y()
        
        # Chart 1
        if trend_data:
            dates = [x[0][5:] for x in trend_data][::-1]
            revs = [x[1] for x in trend_data][::-1]
            plt.figure(figsize=(5, 3.5)) # Compact
            plt.bar(dates, revs, color='#1A237E', alpha=0.8)
            plt.title('Revenue Trend', fontsize=10, fontweight='bold', color='#1A237E')
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.tight_layout()
            plt.savefig(chart1_path, dpi=100)
            plt.close()
            pdf.image(chart1_path, x=10, y=y_charts, w=90)
        else:
             pdf.rect(10, y_charts, 90, 60)
             pdf.text(35, y_charts+30, "No Trend Data")

        # Chart 2
        if top_products:
            sh = sorted(top_products, key=lambda x: x[1])
            labels = [x[0][:15] for x in sh]
            values = [x[1] for x in sh]
            plt.figure(figsize=(5, 3.5))
            plt.barh(labels, values, color='#009688', alpha=0.8)
            plt.title('Top Products', fontsize=10, fontweight='bold', color='#009688')
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.tight_layout()
            plt.savefig(chart2_path, dpi=100)
            plt.close()
            pdf.image(chart2_path, x=110, y=y_charts, w=90)
        
        pdf.set_y(y_charts + 70) # Move past charts

        # --- DETAILED TRANSACTIONS ---
        pdf.set_text_color(0, 0, 0)
        pdf.set_font('Arial', 'B', 14)
        pdf.set_fill_color(230, 230, 250) # Lavender
        pdf.cell(0, 10, "Transaction Details", 0, 1, 'L', fill=True)
        pdf.ln(2)

        # Header
        pdf.set_font('Arial', 'B', 9)
        pdf.set_fill_color(26, 35, 126)
        pdf.set_text_color(255, 255, 255)
        
        # Adjusted Model: Add "ID" column
        col_widths = [15, 40, 40, 45, 15, 15, 20] 
        headers = ["ID", "Time", "Customer", "Item", "Qty", "Price", "Total"]
        
        for i, h in enumerate(headers):
            pdf.cell(col_widths[i], 7, h, 1, 0, 'C', fill=True)
        pdf.ln()

        # Data
        pdf.set_text_color(0, 0, 0)
        pdf.set_font('Arial', '', 8)
        
        fill = False
        pdf.set_fill_color(245, 248, 250) # Very light blue
        
        for row in sales_data:
            # row: id, date, cust, prod, qty, price
            # Need strict extraction
            sid = str(row[0])
            dt = row[1][11:16] # extract HH:MM from YYYY-MM-DD HH:MM:SS
            cust = row[2][:20]
            prod = row[3][:25]
            qty = str(row[4])
            price = f"{row[5]:.2f}"
            total = f"{(row[4] * row[5]):.2f}"
            
            pdf.cell(col_widths[0], 6, sid, 1, 0, 'C', fill=fill)
            pdf.cell(col_widths[1], 6, dt, 1, 0, 'C', fill=fill)
            pdf.cell(col_widths[2], 6, cust, 1, 0, 'L', fill=fill)
            pdf.cell(col_widths[3], 6, prod, 1, 0, 'L', fill=fill)
            pdf.cell(col_widths[4], 6, qty, 1, 0, 'C', fill=fill)
            pdf.cell(col_widths[5], 6, price, 1, 0, 'R', fill=fill)
            pdf.cell(col_widths[6], 6, total, 1, 0, 'R', fill=fill)
            pdf.ln()
            fill = not fill

        pdf.output(filepath)
        
        if os.path.exists(chart1_path): os.remove(chart1_path)
        if os.path.exists(chart2_path): os.remove(chart2_path)
            
        webbrowser.open(f"file://{filepath}")
        return filename
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        return f"Error: {str(e)}"

import urllib.request
def generate_barcode_sheet(barcode_data, product_name, price, quantity):
    """
    Generates a PDF sheet of barcode stickers using BWIP-JS API for image generation.
    Returns the filename of the generated PDF.
    """
    if not FPDF: return "Error: FPDF missing"
    
    try:
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # Sticker dimensions (A4 typically 3x7 or 4x10 grid depending on sticker size)
        # Let's assume standard address labels (~63mm x 38mm), 3 cols, 7 rows = 21 per page
        # A4 W=210mm. Coords.
        
        col_w = 64
        row_h = 34
        cols = 3
        
        # Download Barcode Image
        # Code128 is standard
        api_url = f"https://bwipjs-api.metafloor.com/?bcid=code128&text={barcode_data}&scale=3&height=10&includetext"
        temp_img = os.path.join(tempfile.gettempdir(), f"bc_{barcode_data}.png")
        
        try:
            req = urllib.request.Request(api_url, headers={'User-Agent': 'Mozilla/5.0'})
            with urllib.request.urlopen(req) as response:
                with open(temp_img, 'wb') as out_file:
                    out_file.write(response.read())
        except Exception as e:
            return f"Error downloading barcode: {e}. Check Internet."

        x_start = 10
        y_start = 10
        
        count = 0
        
        for i in range(int(quantity)):
            # Calculate Grid Position
            col = i % cols
            row = (i // cols) % 8 # 8 rows per page
            
            if i > 0 and i % (cols * 8) == 0:
                pdf.add_page()
            
            x = x_start + (col * col_w)
            y = y_start + (row * row_h)
            
            # Draw Border (Optional, helpful for cutting)
            pdf.set_draw_color(200, 200, 200)
            pdf.rect(x, y, col_w-2, row_h-2)
            
            # Text: Product Name (Truncated)
            pdf.set_xy(x, y+2)
            pdf.set_font("Arial", "B", 10)
            pdf.cell(col_w-2, 5, product_name[:20], 0, 1, 'C')
            
            # Image: Barcode
            # Center image roughly
            try:
                pdf.image(temp_img, x=x+5, y=y+8, w=col_w-12, h=15)
            except: pass
            
            # Text: Price
            pdf.set_xy(x, y+24)
            pdf.set_font("Arial", "", 9)
            pdf.cell(col_w-2, 5, f"${price:.2f}", 0, 1, 'C')
            
            count += 1

        # Save
        desktop = os.path.join(os.environ['USERPROFILE'], 'Desktop')
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"Barcodes_{product_name}_{timestamp}.pdf"
        filepath = os.path.join(desktop, filename)
        
        pdf.output(filepath)
        
        # Cleanup
        if os.path.exists(temp_img): os.remove(temp_img)
        
        webbrowser.open(f"file://{filepath}")
        return filename

    except Exception as e:
        import traceback
        traceback.print_exc()
        return f"Error: {str(e)}"
